# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{outdated-gems}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Gibralter"]
  s.date = %q{2010-06-30}
  s.default_executable = %q{outdated_gems}
  s.description = %q{Run `outdated_gems` in a directory containing a Gemfile.lock and it will print the results.}
  s.email = %q{aaron.gibralter@gmail.com}
  s.executables = ["outdated_gems"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "VERSION",
     "bin/outdated_gems",
     "lib/outdated-gems.rb",
     "outdated-gems.gemspec"
  ]
  s.homepage = %q{http://github.com/agibralter/outdated-gems}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Given a Gemfile.lock, list gems that have new versions on rubyforge.org.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bundler>, [">= 0.9.26"])
    else
      s.add_dependency(%q<bundler>, [">= 0.9.26"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0.9.26"])
  end
end

